// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/analytics": {
            "get": {
                "description": "Возвращает агрегированные данные транзакций за указанный период с возможностью группировки, разделения и сортировки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Получить агрегированную аналитику",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дата начала (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата конца (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Группировка (day/week/month/category)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Разделение данных (например по типу транзакции)",
                        "name": "splitby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле для сортировки",
                        "name": "sortby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Направление сортировки (asc/desc)",
                        "name": "sortdir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytic.Analytics"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/analytics/export": {
            "get": {
                "description": "Экспортирует агрегированные данные транзакций за указанный период в CSV-файл",
                "tags": [
                    "Analytics"
                ],
                "summary": "Экспорт аналитики в CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дата начала (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата конца (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Группировка (day/week/month/category)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Разделение данных (например по типу транзакции)",
                        "name": "splitby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле для сортировки",
                        "name": "sortby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Направление сортировки (asc/desc)",
                        "name": "sortdir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV файл",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/items": {
            "get": {
                "description": "Возвращает список всех транзакций с фильтрами",
                "tags": [
                    "Transactions"
                ],
                "summary": "Получить все транзакции",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дата от",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата до",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип транзакции (income/expense)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Категория",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле сортировки",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Направление сортировки (asc/desc)",
                        "name": "sortDir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/transaction.Transaction"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создает транзакцию с типом (income/expense), категорией, суммой, датой и описанием",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Создать новую транзакцию",
                "parameters": [
                    {
                        "description": "Данные транзакции",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SaveTransactionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transaction.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/items/export": {
            "get": {
                "description": "Экспортирует все транзакции за период в CSV-файл",
                "tags": [
                    "Transactions"
                ],
                "summary": "Экспорт транзакций в CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дата от",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата до",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип транзакции (income/expense)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Категория",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле сортировки",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Направление сортировки (asc/desc)",
                        "name": "sortDir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV файл",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/items/{id}": {
            "get": {
                "description": "Возвращает транзакцию по ID",
                "tags": [
                    "Transactions"
                ],
                "summary": "Получить транзакцию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID транзакции",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transaction.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные транзакции по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Обновить транзакцию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID транзакции",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые данные транзакции",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SaveTransactionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transaction.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет транзакцию по ID",
                "tags": [
                    "Transactions"
                ],
                "summary": "Удалить транзакцию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID транзакции",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analytic.Analytic": {
            "type": "object",
            "properties": {
                "Avg": {
                    "type": "number"
                },
                "Count": {
                    "type": "integer"
                },
                "Median": {
                    "type": "number"
                },
                "Percentile90": {
                    "type": "number"
                },
                "Sum": {
                    "type": "number"
                }
            }
        },
        "analytic.AnalyticByType": {
            "type": "object",
            "properties": {
                "All": {
                    "$ref": "#/definitions/analytic.Analytic"
                },
                "Expense": {
                    "$ref": "#/definitions/analytic.Analytic"
                },
                "Income": {
                    "$ref": "#/definitions/analytic.Analytic"
                }
            }
        },
        "analytic.AnalyticGroup": {
            "type": "object",
            "properties": {
                "Data": {
                    "$ref": "#/definitions/analytic.AnalyticByType"
                },
                "GroupKey": {
                    "type": "string"
                }
            }
        },
        "analytic.Analytics": {
            "type": "object",
            "properties": {
                "Groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytic.AnalyticGroup"
                    }
                },
                "Summary": {
                    "$ref": "#/definitions/analytic.AnalyticByType"
                }
            }
        },
        "dto.SaveTransactionReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "type": {
                    "description": "income|expense",
                    "type": "string"
                }
            }
        },
        "transaction.Transaction": {
            "type": "object",
            "properties": {
                "Amount": {
                    "type": "number"
                },
                "Category": {
                    "type": "string"
                },
                "Date": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "ID": {
                    "type": "string"
                },
                "Type": {
                    "$ref": "#/definitions/transaction.TransactionType"
                }
            }
        },
        "transaction.TransactionType": {
            "type": "string",
            "enum": [
                "income",
                "expense"
            ],
            "x-enum-varnames": [
                "Income",
                "Expense"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "salesTracker API",
	Description:      "API для управления продажами и транзакциями.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
